name: ResourceWorld
version: ${project.version}
main: me.nik.resourceworld.ResourceWorld
api-version: 1.13
authors: [Nik, GZimmer (fork)]
description: ${project.description}
website: https://discord.gg/m7j2Y9H
softdepend: [PlaceholderAPI]
commands:
  resource:
    description: Unlimited resources!
    aliases: [resourceworld, rw]
permissions:
  rw.tp:
    description: Randomly Teleport To The Resource World!
    default: true
  rw.tp.nether:
    description: Randomly Teleport To The Nether Resource World!
  rw.tp.end:
    description: Randomly Teleport To The End Resource World!
  rw.tp.*:
    description: Access To Teleport To All The Resource Worlds!
    default: op
    children:
      rw.tp: true
      rw.tp.nether: true
      rw.tp.end: true
  rw.admin:
    description: Access to the Resource World admin commands!
    default: op